### ISSUE TITLE
New instructions?

### ISSUE THREAD

**Issue by Vaguery** [lspector/Clojush#123]
Any advice for a file structure or convention for adding instructions to the "standard suite" vs problem-specific ones?

I have a mind to bring over some of the stack-focused instructions from PushSwift and Nudge, especially the `[stack_name]_switch` and `[stack_name]_filter` families of instructions, and I'm not sure how to structure the `use` appropriately.

**Comment by thelmuth** [comment]
It depends. If it seems like something others might want to use, add it to the standard suite; if it's problem-specific, put it in the problem file.

If you make a `[stack_name]_X` function for a bunch of stacks, the convention is to put it in the common.clj file: https://github.com/lspector/Clojush/blob/master/src/clojush/instructions/common.clj

Otherwise, put the instruction in the file associated with the type of the stack.
