### ISSUE TITLE
How do I invoke `lein run my.example` so it uses more of my copious CPU?

### ISSUE THREAD

**Issue by Vaguery** [lspector/Clojush#144]
I just moved my little learning-by-doing example over to the Big Server machine in our house, and invoked it (as I had on my laptop) with `lein run clojush.problems.tozier.winkler01`. But it's only using a single core on the big multicore CPU. Is this a JVM issue, a `lein` issue (and if so, please point out how to fix), or is there an argument somewhere in the codebase I should be toggling?

**Comment by Vaguery** [comment]
[closed: I was looking at the low-CPU phase of the algorithm, and it eventually got to the high-CPU phase.]

**Comment by thelmuth** [comment]
We've actually had some problems with this in the past, the details of which I am not certain. It would be good to double check that you're seeing the CPU utilization that you think you should be!

**Comment by lspector** [comment]
One thing that I think has been the root of related problem in the past has been lazy evaluation. I can't recall the details (or if I really ever figured this out), but I've found, unfortunately, that in Clojure it's often good to use mapv instead of map, or other tricks to ensure that sequences are fully realized unless you *really* want them to be lazy. If you have laziness in your problem definition then you might want to stamp it out. 

-Lee


> On Jul 12, 2015, at 12:19 PM, Tom Helmuth <notifications@github.com> wrote:
> 
> We've actually had some problems with this in the past, the details of which I am not certain. It would be good to double check that you're seeing the CPU utilization that you think you should be!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lspector/Clojush/issues/144#issuecomment-120737516>.
> 

--
Lee Spector, Professor of Computer Science
Director, Institute for Computational Intelligence
Cognitive Science, Hampshire College
893 West Street, Amherst, MA 01002-3359
lspector@hampshire.edu, http://hampshire.edu/lspector/
Phone: 413-559-5352, Fax: 413-559-5438
