### ISSUE TITLE
There is one Clojure struct defined

### ISSUE THREAD

**Issue by Vaguery** [lspector/Clojush#150]
I was trying to build the convenience function I mentioned in #148 and have to ask if there's an particular reason that `push-state` is a `struct` instead of a `record`.

**Comment by lspector** [comment]
Quite confused about this question, because they *are* records, not structs. I'd prefer them to be structs (maps) to stay in pure clojure, and because this would make associated macros simpler. They used to be structs (maps), but I was convinced by chatter on the clojure list to make them records, and when I tried it I found that that did indeed make them marginally faster. So I changed the to be records, which they are now. What makes you think otherwise?

**Comment by Vaguery** [comment]
Sorry, I'm still learning the particulars of Clojure as I work through these small exploratory projects.

`push-state` is defined, as far as I can tell, using `defstruct`, and as I was trying to work through how to manipulate it I encountered the comments in [the Clojure docs, here](https://clojuredocs.org/clojure.core/defstruct).
