### ISSUE TITLE
Inconsistent approach to empty vector_* types

### ISSUE THREAD

**Issue by Vaguery** [lspector/Clojush#152]
I'm working through the tests for the `enumerator` type, and noticing that the [_recognizers_ for vector instances](https://github.com/lspector/Clojush/blob/5cfed3fd322dfd188ba4282f2757be7723b534a9/src/clojush/util.clj#L18-L21) are a bit concerning. Mainly I am wondering about edge cases, for instance one in which `vector_integer_rest` is applied to an argument with exactly one element. The result is not pushed to `:exec`, but rather directly to `:vector_integer`, and I just checked this with this passing test:

```clojure
(def vi-state-with-1-element (push-state-from-stacks :vector_integer '([77])))

(facts "vector_integer_rest can produce an empty vi result"
  (top-item :vector_integer (execute-instruction 'vector_integer_rest vi-state-with-1-element)) => []
  )
```

I assume there are some other places where a `vector_*` could produce an empty vector as well.

This is not in itself a problem, but now look again at [the interpreter's recognizers](https://github.com/lspector/Clojush/blob/5cfed3fd322dfd188ba4282f2757be7723b534a9/src/clojush/util.clj#L18-L21). These do not push empty vectors to _any_ stack.

I ask because I'm about to write code for moving the pointer through an `Enumerator`'s stored `seq`, and I need to have a better sense of whether you _want_ empty vectors to be present on the stacks before I write tests for `Enumerators` that behave right when they _contain_ empty vectors.

I've already written the code which "unwraps" an `Enumerator` object and pushes the `seq` it contains onto `:exec`, but I did not think before now to check whether an _empty_ `seq` would be recognized by the interpreter. I imagine it will raise an exception.

**Comment by thelmuth** [comment]
Ah yes, the empty vector problem. Do you see the problem?

The problem is that if you have an empty vector in a program (for instance, that appeared there as an input or from an ERC), *you can't tell what type of vector it is*. So, while you're correct that the code you pointed to doesn't recognize empty vectors, I had to hack it in somewhere else.

When I was working on this, Lee and I agreed that the best approach would be to push empty vectors onto ALL of the vector stacks, since you couldn't tell what type they were. [This code is here](https://github.com/lspector/Clojush/blob/5cfed3fd322dfd188ba4282f2757be7723b534a9/src/clojush/interpreter.clj#L21). This is a solution I'm not particularly happy with, but it was the best we came up with at the time.

Now that I'm thinking about it, there might be a better solution by adding metadata to empty vectors (or maybe all vectors) that tells what type of vector they are. But, I'm not that familiar with metadata, and I'm not sure how well that would work in practice. It might require all vector-manipulating functions to add metadata to things, which could be a lot of work.

**Comment by Vaguery** [comment]
The big issue for me is that your code makes it possible for the interpreter to deal with an empty vector. Don't care where it goes (that's a separate issue): this at least relives me from having to check the contents.

**Comment by Vaguery** [comment]
(Actually "the problem" is perhaps a bit deeper, and involves where instructions push their results. Some instructions use the `:exec` stack, while others skip steps and push their results straight to the result stacks. I'll probably do an accounting sometime soon, when I start to test the existing instructions more completely.
