### ISSUE TITLE
Doubled Automatic Commits?

### ISSUE THREAD

**Issue by thelmuth** [lspector/Clojush#187]
@saulshanabrook I noticed that the automatic commits are [doing 2 commits in a row](https://github.com/lspector/Clojush/commits/master), just changing the version number whenever @lspector pushes. Is that intended

**Comment by saulshanabrook** [comment]
Yeah it is intended. Since all development happens on a `-SNAPSHOT` version, it need to remove the `-SNAPSHOT`, before pushing to clojars. So it commits this so we have a commit that has the repo exactly when it was released, and then another commit to get on the next SNAPSHOT.

This is the default way lein deals with releases: https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md#releasing-simplified

**Comment by thelmuth** [comment]
Cool, thanks!

**Comment by Vaguery** [comment]
Actually, invoking `lein deploy clojars` (with the explicit target) is perfectly happy to send a `-SNAPSHOT` item out. In fact, that's actually _good_, since dependencies that include the `-SNAPSHOT` suffix are downloaded every day by users who link to them. If the `-SNAPSHOT` suffix is not added, then you have to actively change the commit number every time anybody commits.

Which I guess you could do. ?

**Comment by saulshanabrook** [comment]
@Vaguery Could you elaborate on what that would be good? What do you mean "actively change commit number"?

**Comment by Vaguery** [comment]
Well, when I'm actively developing code, as long as it's fully tested before each commit (and to do otherwise is dumb) I can send it out into the world as a clojar with the same version number and a `-SNAPSHOT` suffix. Anybody who, for example, includes a dependency for [my library](https://github.com/Vaguery/answer-factory-clj/blob/master/project.clj#L5) in their project will _automatically_ download a new copy every 24 hours, as long as the suffix is present. If I know how to semantic, then by the time I actually increment from 0.1.8 to 0.1.9 I will have a reason—a substantial new feature or two, for example.

If somebody includes a dependency to a release version (without `-SNAPSHOT`), that's also fine. It's just a different social signal not to worry about there ever being any changes in the codebase, since _that dependency link will not automatically be updated_.

It's just a distinction in the way people are expected to use the code. I'm not really following the details of the Clojush maintenance any more, so I don't know what the changelog is like actually. But I don't think (glancing over it) there's any reason you should be changing the version number _and_ adding the `-SNAPSHOT` suffix. That's redundant, and actually undermines the use of the suffix so it doesn't do anything.
